### ISSUE TITLE
Невозможность зарегистрироваться

### ISSUE THREAD

**Issue by Surikat12** [ilyshaav/Tiopo_pr1_Eremenko_Viyugina_Petkevich#1]
Программа аварийно завершает работу при нажатии на кнопку "Регистрация" при входных данных, удовлетворяющих спецификации. Сообщение об ошибке представлено на скриншоте ниже.
![Сообщение об ошибке](https://user-images.githubusercontent.com/55013562/154521172-b3baa6e0-2b7e-4cd5-aea8-73bebc4bb7f7.png)

**Comment by ilyshaav** [comment]
При регистрации используйте буквы только латинского алфавита.

**Comment by Surikat12** [comment]
Это решило проблему.

**Comment by ilyshaav** [comment]
Внесем исправления в спецификацию.
