### ISSUE TITLE
Bad UI/UX в TextBox

### ISSUE THREAD

**Issue by amishanov** [ilyshaav/Tiopo_pr1_Eremenko_Viyugina_Petkevich#3]
На форме аутентификации в текстовых полях вставлен полноценный текст, вместо подсказки. То есть поле не становиться пустым при выделении, а стёртые надписи "Логин" и "Pin" не появятся снова. 
UPD: Как выяснилось, эта проблема характерна для всех полей ввода данных

**Comment by ilyshaav** [comment]
Проблема принята к сведению, исправим.
