### ISSUE TITLE
Программа аварийно завершает работу при вводе букв в поле для цифр.

### ISSUE THREAD

**Issue by Surikat12** [ilyshaav/Tiopo_pr1_Eremenko_Viyugina_Petkevich#4]
Программа аварийно завершает работу при вводе букв в поле "Сумма к оплате"
![Сообщение об ошибке 2](https://user-images.githubusercontent.com/55013562/154528889-8e7658fd-8526-440a-8922-861828006bdf.png)

**Comment by ilyshaav** [comment]
Проблема принята к сведению, исправим. Проблема возникает из-за ввода русских букв, вводи те только английские буквы.
